# Generated by Django 4.2.6 on 2023-10-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('no_reviews', models.IntegerField(null=True)),
                ('review_list', models.JSONField(null=True)),
                ('no_products', models.IntegerField(null=True)),
                ('product_dict', models.JSONField(null=True)),
                ('mean_rating', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=255, null=True)),
                ('total_rating', models.FloatField(null=True)),
                ('response_rate_percent', models.FloatField(null=True)),
                ('days', models.IntegerField(null=True)),
                ('no_products', models.IntegerField(null=True)),
                ('response_speed', models.CharField(max_length=50, null=True)),
                ('no_follower', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('avg_rating', models.FloatField(null=True)),
                ('total_rating', models.IntegerField(null=True)),
                ('total_sold', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('fav_count', models.IntegerField(null=True)),
                ('qty_avail', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('img_src', models.CharField(max_length=255, null=True)),
                ('merchant_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sitApp.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('content', models.TextField(null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('product_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sitApp.product')),
                ('user_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sitApp.customer')),
            ],
        ),
    ]
