# Generated by Django 4.2.6 on 2023-10-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='no_products',
            new_name='no_product',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='no_reviews',
            new_name='no_review',
        ),
    ]
