# Generated by Django 4.2.6 on 2023-10-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_norm_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='count_norm_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='credibility_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='merchant_class',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='neg_words',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pos_words',
            field=models.TextField(null=True),
        ),
    ]
