# Generated by Django 4.2.6 on 2023-10-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitApp', '0002_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer_id',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
        migrations.AddField(
            model_name='customer',
            name='mean_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_products',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_reviews',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='product_dict',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='review_list',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='joined',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='no_products',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='response_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='response_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fav_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='img_src',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mall',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_avail',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='merchant_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sitApp.merchant'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='merchant_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sitApp.merchant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
