# Generated by Django 4.2.6 on 2023-10-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitApp', '0002_rename_no_products_customer_no_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
    ]
