# Generated by Django 4.2.6 on 2023-10-11 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitApp', '0003_rename_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
