# Generated by Django 4.2.6 on 2023-10-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitApp', '0003_remove_product_neg_words_remove_product_pos_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='min_dist_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
