# Generated by Django 4.2.6 on 2023-10-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitApp', '0003_rename_customer_id_review_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
    ]
