# Generated by Django 4.2.6 on 2023-10-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitApp', '0004_rename_user_name_review_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='product_dict',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='review_list',
            field=models.TextField(null=True),
        ),
    ]
