# Generated by Django 4.2.6 on 2023-10-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitApp', '0004_remove_review_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sitApp.customer'),
        ),
    ]
