# Generated by Django 4.2.6 on 2023-10-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitApp', '0005_review_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
