# Generated by Django 4.2.6 on 2023-10-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitApp', '0005_alter_user_product_dict_alter_user_review_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
